### PR TITLE
UKP repository inclusion and gitignore modification for the Eclipse IDE.

### PR DESCRIPTION
**Pull request by rudgern**
Now the project uses the UKP repository to download DK-PRO 1.8.0-SNAPSHOT.

### CODE REVIEW

**Comment by reckart** [comment]
Hi. Thank you for the pull request. The changes in the PR appear to be more that what you specify, including whitespace changes, breaking the formatting of a license header, and a change to an example file. Changes in a PR should be minimal and focussed on a particular issue. So here I see at least three PRs:

* update to DKPro Core 1.8.0-SNAPSHOT
* modification of .gitignore
* Adding of the TikaReader example

**Comment by reckart** [comment]
Focussed PRs make it easier to review them and to discuss them. It can also improve the uptake of the PR as good changes do not need to be disentangled from changes that are not ready yet for inclusion.

**Comment by carschno** [comment]
Following up Richard's comment: thank you in particular for the TikaReader example! Would you be able to add an issue for that, separate the related patch(es), and commit them in a dedicated pull request, while referring to the previously created issue in the commit message?
This also holds for the other parts of your commit: please add an issue, commit a specifically tailored, minimal patch, and refer to the issue in the commit message.
Thank you for your contribution and please feel free to ask for more information if necessary!

**Comment by reckart** [comment]
@carschno Issues and PRs appear to be sharing the same number space on GitHub - basically it seems that a PR is just an issue with an associated branch. I don't think creating separate issues is necessary here. In the commit message, one can refer to the PR by number as we usually do for issues.

**Comment by rudgern** [comment]
First of all, I would like to congratulate you all for the great DKPro project. It is a really amazing work bringing together the several natural language processing tools that are available. To my surprise, I even found an experimental wrapper CoGrOO. I am starting with NLP to create an implementation in my master's dissertation, but I can say that the DKPro has made my life much easier. Then again, congratulations.

About this PR, thank you both for the guidance. In fact, I should not have requested it with formatting changes and many different modifications. That was my first experience with PR. Indeed, only the first commit should have participated in the PR if there were not those problems that you reported. The TikaReader example was in draft work. I should have read more about the PR process before this PR. I am sorry about that.

I ended up closing this PR to rebase a git project before my changes. As soon as possible, I will include these changes correctly and I will make a new PR.

It was a pleasure to have this first contact with you.

**Comment by reckart** [comment]
Thanks :) We're looking forward the the new PRs.

**Pull request closed without merging**
